server.port = 8080
spring.application.name=stadium-parika

################# POSTGRESQL CONFIGURATION ##################
spring.datasource.url: jdbc:postgresql://dpg-d6job215pdvs73dd0a5g-a/stadium_parika
spring.datasource.username: stadium_parika_user
spring.datasource.password: xjuzfIQ1gESDPnLDJ7NrX0HHoN06nmNb
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql=true

##### PORT #####
#server.port=${PORT:8080}

################# MYSQL CONFIGURATION #######################
#server.port = 8084
#spring.datasource.url = jdbc:mysql://localhost:3306/stadium_parika
#spring.datasource.username = root
#spring.datasource.password =
#spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Swagger Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.server.base-url=https://admin.parikapp.com
springdoc.cors.enabled=true
