spring.application.name=stadium-parika

################# MYSQL CONFIGURATION #######################
server.port = 8084
spring.datasource.url = jdbc:mysql://localhost:3306/stadium_parika
spring.datasource.username = root
spring.datasource.password =
spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.server.base-url=https://admin.parikapp.com
springdoc.cors.enabled=true
